/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

"""
法1：利用额外的数组存储两个字符串的字符，数组中数值为奇数的必定是额外的字符
法2：利用ascii码值，加减相抵，多出来的就是额外的字符

Solution - Java

"""


class Solution {
    public char findTheDifference(String s, String t) {
        
        //Solution - 1
        
        int[] num = new int[26];
        char result = 'a';
        for(int i = 0; i < s.length(); i++){
            num[s.charAt(i) - 'a'] += 1;
        }
        for(int i = 0; i < t.length(); i++){
            num[t.charAt(i) - 'a'] += 1;
        }
        for(int i = 0; i < num.length; i++){
            if(num[i] % 2 != 0) {
                result = (char)(i + 'a');
            }
        }
        return result;
        
        //Solution - 2
        
        int charCode = t.charAt(s.length());
        // Iterate through both strings and char codes
        for (int i = 0; i < s.length(); ++i) {
              charCode -= (int)s.charAt(i);
              charCode += (int)t.charAt(i); 
        }
        return (char)charCode;
    }
}
